spring.application.name=KnockIn

spring.profiles.active=test
spring.profiles.include=secret-common

spring.profiles.group.prod=secret-prod
spring.profiles.group.test=secret-test

springdoc.use-fqn=true
popular.count.size=10

policy.board.comeable-date-visible-grace-days=7
policy.board.image-max-count=10
policy.board.thumbnail-image-max-count=1
policy.board.hot-badge-min-interest-count=10
policy.chat.room-limit-per-member=5
policy.request-alarm.expire-days=7

policy.roommate-score.perfect-score=100
policy.roommate-score.important-pattern-multiplier=2

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=500MB

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}